<?php

namespace BilimBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BilimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilimRepository extends EntityRepository
{
}
