region_index:
    path:     /
    defaults: { _controller: "BilimBundle:Region:index" }
    methods:  GET

region_show:
    path:     /{id}/show
    defaults: { _controller: "BilimBundle:Region:show" }
    methods:  GET

region_new:
    path:     /new
    defaults: { _controller: "BilimBundle:Region:new" }
    methods:  [GET, POST]

region_edit:
    path:     /{id}/edit
    defaults: { _controller: "BilimBundle:Region:edit" }
    methods:  [GET, POST]

region_delete:
    path:     /{id}/delete
    defaults: { _controller: "BilimBundle:Region:delete" }
    methods:  DELETE
