student_index:
    path:     /
    defaults: { _controller: "BilimBundle:Student:index" }
    methods:  GET

student_show:
    path:     /{id}/show
    defaults: { _controller: "BilimBundle:Student:show" }
    methods:  GET

student_new:
    path:     /new
    defaults: { _controller: "BilimBundle:Student:new" }
    methods:  [GET, POST]

student_edit:
    path:     /{id}/edit
    defaults: { _controller: "BilimBundle:Student:edit" }
    methods:  [GET, POST]

student_delete:
    path:     /{id}/delete
    defaults: { _controller: "BilimBundle:Student:delete" }
    methods:  DELETE
    methods:  [GET, POST]

student_list_by_test:
    path:     /list/by/{id}
    defaults: { _controller: "BilimBundle:Student:listByTest" }

student_generator:
    path:     /generator/by/test
    defaults: { _controller: "BilimBundle:Student:generator" }

student_generate_random:
    path:     /generator/random
    defaults: { _controller: "BilimBundle:Student:randomGenerate" }
