suroo_index:
    path:     /
    defaults: { _controller: "BilimBundle:Suroo:index" }
    methods:  GET

suroo_show:
    path:     /{id}/show
    defaults: { _controller: "BilimBundle:Suroo:show" }
    methods:  GET

suroo_new:
    path:     /new
    defaults: { _controller: "BilimBundle:Suroo:new" }
    methods:  [GET, POST]

suroo_edit:
    path:     /{id}/edit
    defaults: { _controller: "BilimBundle:Suroo:edit" }
    methods:  [GET, POST]

suroo_delete:
    path:     /{id}/delete
    defaults: { _controller: "BilimBundle:Suroo:delete" }
    methods:  DELETE

suroo_generate_random:
    path:     /generate/quesetions
    defaults: { _controller: "BilimBundle:Suroo:generateRandom" }

suroo_generate:
    path:     /generate/suroo
    defaults: { _controller: "BilimBundle:Suroo:generate" }
